model_for: sft
model: gpt2-large
dtype: bfloat16


temperature: 0.7

batch_size: 64
gradient_step: 2  # gradient accumulation steps
max_gradient: 1
lr: 0.00005
min_lr: 0.000005
epoch: 1
eval_batch_size: 32

activation_checkpointing: True

checkpoint_type: FULL_STATE_DICT # SHARDED_STATE_DICT, or FULL_STATE_DICT
checkpoint_folder: checkpoint
model_save_name: sft_gpt2-large
dist_checkpoint_root_folder: checkpoint
dist_checkpoint_folder: shard
save_using_num_threads: 8
