model_for: reward
model: gpt2
dtype: bfloat16

ckpt: saved_ckpt/sft_gpt2_fsdp.pt
ckpt_type: sft


temperature: 0.7
batch_size: 32  # to reduce memory footprint
lr: 0.00005
min_lr: 0.000005
epoch: 1

activation_checkpointing: True

checkpoint_type: FULL_STATE_DICT # SHARDED_STATE_DICT, or FULL_STATE_DICT
checkpoint_folder: checkpoint
model_save_name: reward_gpt2
dist_checkpoint_root_folder: checkpoint
dist_checkpoint_folder: shard
save_using_num_threads: 4

